fix a bug for jsonp request
### bug description
since a new case clause has been added to the settings.dataType-handling block, unfortunately, this branch will break the original code, the following code block which is used to handle settings.data will never get a chance to run.

### code snippet which reveals the bug
```
af.ajax({
  url: 'http://sample/do_query.jsonp?callback=?',
  type: 'get',
  data: {a: 1, b: 2},
  dataType: 'jsonp',
  success: function(data) {
    console.log(data);
  },
  error: function() {
    console.err(arguments);
  }
})
```

### how to fix?
switch the settings.dataType and settings.data code block.